name: Main CI Workflow

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2.3.1
      - run: pip install -r requirements.dev
      - run: pytest